### PR TITLE
Add lumosmaxima

### PR DESCRIPTION
**Pull request by gyles**

### CODE REVIEW

**Comment by championballer** [comment]
@gyles Can you resolve the merge conflict? I can merge after that. Thanks.

**Comment by gyles** [comment]
@championballer done thanks!

**Review by championballer — APPROVED** [review]

**Comment by championballer** [comment]
Thanks. Happy Hacktoberfest. :)

**Comment by gyles** [comment]
Happy Hacktoberfest! 😃

**Pull request merged**
