### PR TITLE
riddikulus & aparecium

### PR DESCRIPTION
**Pull request by Ventrosky**
Add more spells #34 

aparecium: ls -a
riddikulus: apt-get moo

### CODE REVIEW

**Comment by championballer** [comment]
Hey @Ventrosky, can you add the spell to the readme as well? All else looks great.

**Comment by Ventrosky** [comment]
sure, forgot about it

**Comment by Ventrosky** [comment]
Done, thxs

**Review by championballer — APPROVED** [review]

**Comment by championballer** [comment]
Thanks. Happy Hacktoberfest to you. :)

**Pull request merged**
