### PR TITLE
[WIP?] Script Install Recording

### PR DESCRIPTION
**Pull request by kayew**
Solves #50 

Please let me know if I should change the script in any way. If you see nothing wrong with it, please accept the PR.

### CODE REVIEW

**Review by championballer — CHANGES_REQUESTED** [review]
I was hoping more on the lines of something that does not require the user to redirect to a different tab. Please embed as a gif.

**Comment by kayew** [comment]
Well, I was hoping that asciinema's way of embeding would work. It didn't. Give me some time to see how I can properly embed this.

**Comment by championballer** [comment]
Cool.

**Comment by kayew** [comment]
It took some time to set up [terminalizer](https://github.com/faressoft/terminalizer/issues) and render the gif, but It should all be good now. Let me know what you think.

**Review by championballer — CHANGES_REQUESTED** [review]
Screenshot 2019-10-14 at 8 39 27 AM

Doesn't seem to working for now @kaewhyes

**Comment by kayew** [comment]
This is an issue on your end. It is visible on my fork, and in vscode.

**Review by championballer — APPROVED** [review]

**Comment by championballer** [comment]
Awesome job. Thanks. :)

**Comment by kayew** [comment]
No problem!

**Pull request merged**
