### PR TITLE
Prettier README file:, nicer headings and better spell listing

### PR DESCRIPTION
**Pull request by malte-j**
In reference to #35

### CODE REVIEW

**Review by championballer — CHANGES_REQUESTED** [review]
Can you please resolve the conflicts?

**Comment by malte-j** [comment]
All conflicts should be resolved

**Comment by malte-j** [comment]
Also, the raw files for the images can be found at "https://www.figma.com/file/B6w9vdoVTOYEDSgedXb4sq/Magical-Commands"

**Review by championballer — APPROVED** [review]

**Comment by championballer** [comment]
LGTM.

**Pull request merged**
